# Generated by Django 5.1.3 on 2025-10-23 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('courses', '0005_course_average_rating_course_total_reviews_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_on']},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['course', '-sent_on'], name='chat_messag_course__8dc63e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', '-sent_on'], name='chat_messag_user_id_a13aa9_idx'),
        ),
    ]
