"""
Django settings for config_educa project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-key-only-for-local-development')

# SECURITY WARNING: don't run with debug turned on in production!
# Safe-by-default: base stays off; local.py opts into DEBUG=True for development.
DEBUG = False

ALLOWED_HOSTS = ["educto.io", "www.educto.io", "127.0.0.1", "localhost"]

# Application definition

INSTALLED_APPS = [
    'courses.apps.CoursesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Added for SEO
    'django_extensions',
    'students.apps.StudentsConfig',
    'embed_video',
    'redisboard',
    'rest_framework',
    'chat',
    'channels',
    'analytics.apps.AnalyticsConfig',  # Analytics & Tracking
    'reviews.apps.ReviewsConfig',  # Course Reviews
    'certificates.apps.CertificatesConfig',  # Course Certificates
    'tailwind',
    'theme',
    'shared.apps.SharedConfig',
    'django_htmx',
    # --- New domain apps (Nov 2025 scaffold) ---
    'quizzes.apps.QuizzesConfig',
    'ai_tools.apps.AIToolsConfig',
    'forum.apps.ForumConfig',
    'gamification.apps.GamificationConfig',
    'notifications.apps.NotificationsConfig',
    'mentorship.apps.MentorshipConfig',
    'peer_review.apps.PeerReviewConfig',
    'privacy.apps.PrivacyConfig',
    'honeypot.apps.HoneypotConfig',
    'django_celery_beat',
]

# Email backend — console for dev; override in prod.py with real SMTP / SES.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_FROM_EMAIL', 'noreply@educto.io')

# --- Celery ---------------------------------------------------------------
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/2')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/3')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_EAGER', 'False').lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True
# Periodic schedule — wire with django-celery-beat in prod for DB-driven cron.
CELERY_BEAT_SCHEDULE = {
    'expire_old_exports': {
        'task': 'privacy.tasks.expire_old_exports',
        'schedule': 60 * 60 * 6,  # every 6h
    },
    'process_scheduled_deletions': {
        'task': 'privacy.tasks.process_scheduled_deletions',
        'schedule': 60 * 60,  # every hour
    },
    'honeypot_analyze': {
        'task': 'honeypot.analyze',
        'schedule': 60 * 60,  # hourly threat-intel aggregation
    },
}

# --- Honeypot -------------------------------------------------------------
# Comma-separated list of addresses that receive intrusion alerts (empty = none).
SECURITY_ALERT_EMAILS = [
    e.strip() for e in os.environ.get('SECURITY_ALERT_EMAILS', '').split(',') if e.strip()
]

# --- AI tool API keys (read from env; never commit) -----------------------
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_TOOLS_DEFAULT_PROVIDER = os.environ.get('AI_TOOLS_DEFAULT_PROVIDER', 'fake')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Honeypot probe tripwire — fail-open, runs early so scanner probes are
    # logged before the rest of the stack. No-op for all legitimate paths.
    'honeypot.middleware.HoneypotProbeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config_educa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config_educa.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config_educa.wsgi.application'
ASGI_APPLICATION = 'config_educa.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = reverse_lazy('dashboard')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 60 * 15  # 15 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'config_educa'

INTERNAL_IPS = [
    '127.0.0.1',
]
STATIC_ROOT = BASE_DIR / 'static'

# Redis settings for module tracking
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1

# -- Foundry UI / Tailwind ---------------------------------------------------
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = os.environ.get('NPM_BIN_PATH', '/opt/homebrew/bin/npm')

# Feature flag: opt into the new Foundry-style base.html during rollout.
USE_FOUNDRY_UI = os.environ.get('USE_FOUNDRY_UI', 'False').lower() == 'true'
