# Generated by Django 5.1.3 on 2025-10-23 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews', max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created'], name='courses_cou_created_6f51ad_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', '-created'], name='courses_cou_owner_i_be1a65_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', '-created'], name='courses_cou_subject_d0a713_idx'),
        ),
    ]
