# Generated by Django 4.2.18 on 2026-05-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_average_rating_course_total_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='captions_vtt',
            field=models.FileField(blank=True, help_text='WebVTT captions file.', null=True, upload_to='captions/'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full text transcript for accessibility and search.'),
        ),
    ]
