# Generated by Django 4.2.18 on 2026-05-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_captions_vtt_video_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('bloom_level', models.CharField(blank=True, help_text="Bloom's taxonomy verb (remember/understand/apply/analyze/evaluate/create).", max_length=20)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.skilldomain')),
            ],
            options={
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='Action-verb-led outcome, e.g. "Design a multi-step prompt chain."')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='courses.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='courses.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_in_courses', to='courses.skill')),
            ],
            options={
                'ordering': ['-is_primary', 'skill'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='courses', through='courses.CourseSkill', to='courses.skill'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['domain', 'name'], name='courses_ski_domain__948d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['course', 'order'], name='courses_lea_course__cda06b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill')},
        ),
    ]
