# Generated by Django 5.1.3 on 2025-10-23 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_average_rating_course_total_reviews_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('play', 'Play'), ('pause', 'Pause'), ('complete', 'Complete'), ('download', 'Download')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='For video/audio content', null=True)),
                ('position_seconds', models.IntegerField(blank=True, help_text='Playback position', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Interaction',
                'verbose_name_plural': 'Content Interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content', '-timestamp'], name='analytics_c_user_id_66bf49_idx'), models.Index(fields=['content', '-timestamp'], name='analytics_c_content_df64fb_idx'), models.Index(fields=['interaction_type', '-timestamp'], name='analytics_c_interac_1d738a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course View',
                'verbose_name_plural': 'Course Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['course', '-viewed_at'], name='analytics_c_course__287a82_idx'), models.Index(fields=['user', '-viewed_at'], name='analytics_c_user_id_392be2_idx'), models.Index(fields=['session_id', '-viewed_at'], name='analytics_c_session_7c8108_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('course_view', 'Course View'), ('enroll_click', 'Enroll Button Click'), ('enrolled', 'Enrolled'), ('first_module_accessed', 'First Module Accessed'), ('course_completed', 'Course Completed')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_events', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Event',
                'verbose_name_plural': 'Enrollment Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'course', '-timestamp'], name='analytics_e_user_id_21dac9_idx'), models.Index(fields=['event_type', '-timestamp'], name='analytics_e_event_t_238f21_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('modules_completed', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('courses_accessed', models.ManyToManyField(related_name='streak_records', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Streak',
                'verbose_name_plural': 'Learning Streaks',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_l_user_id_26849b_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'module'], name='analytics_m_user_id_de2878_idx'), models.Index(fields=['module', 'status'], name='analytics_m_module__811e8d_idx'), models.Index(fields=['-last_accessed'], name='analytics_m_last_ac_d53cc4_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='analytics_u_user_id_a4851b_idx'), models.Index(fields=['session_key'], name='analytics_u_session_9b7b71_idx')],
            },
        ),
    ]
