# Generated by Django 4.2.18 on 2026-05-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_video_captions_vtt_video_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', 'Local / self-hosted'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Name of env var holding the API key (do not store the key itself).', max_length=100)),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Prompt body with {{placeholders}}.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of {name, label, default} for placeholders.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to='courses.course')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='ai_tools.aitool')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_run_limit', models.PositiveIntegerField(default=100)),
                ('monthly_token_limit', models.PositiveIntegerField(default=200000)),
                ('runs_this_period', models.PositiveIntegerField(default=0)),
                ('tokens_this_period', models.PositiveIntegerField(default=0)),
                ('period_started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SandboxRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('cost_micros', models.PositiveIntegerField(default=0, help_text='Estimated cost in millionths of a USD.')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai_tools.prompttemplate')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_tools.aitool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', '-created'], name='ai_tools_sa_user_id_646d15_idx'), models.Index(fields=['tool', '-created'], name='ai_tools_sa_tool_id_baed5b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['tool', '-created'], name='ai_tools_pr_tool_id_2956d6_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['-use_count'], name='ai_tools_pr_use_cou_4fd49d_idx'),
        ),
    ]
