# Generated by Django 4.2.18 on 2026-05-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('course_updates', models.BooleanField(default=True)),
                ('forum_replies', models.BooleanField(default=True)),
                ('mentor_messages', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('course_update', 'Course Update'), ('forum_reply', 'Forum Reply'), ('badge_earned', 'Badge Earned'), ('certificate_ready', 'Certificate Ready'), ('quiz_graded', 'Quiz Graded'), ('mentor_message', 'Mentor Message'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created'], name='notificatio_user_id_daba57_idx'), models.Index(fields=['user', 'kind', '-created'], name='notificatio_user_id_3c33d2_idx')],
            },
        ),
    ]
