# Generated by Django 4.2 on 2026-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('course_update', 'Course Update'), ('forum_reply', 'Forum Reply'), ('badge_earned', 'Badge Earned'), ('certificate_ready', 'Certificate Ready'), ('quiz_graded', 'Quiz Graded'), ('mentor_message', 'Mentor Message'), ('security_alert', 'Security Alert'), ('system', 'System')], max_length=30),
        ),
    ]
