# Generated by Django 5.1.3 on 2025-10-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_user_id_488ebb_idx',
            old_name='certificate_user_id_9f8a6d_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_certifi_5672de_idx',
            old_name='certificate_certifi_7e3b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_verific_e033f7_idx',
            old_name='certificate_verific_8a7c9d_idx',
        ),
    ]
