# Generated by Django 4.2 on 2026-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecoyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('display_role', models.CharField(default='Administrator', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='HoneypotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('fake_admin_login', 'Fake admin login'), ('decoy_endpoint', 'Decoy endpoint'), ('exposed_file', 'Exposed file probe'), ('decoy_account_login', 'Decoy account login'), ('tripwire', 'Tripwire link')], max_length=24)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('attempted_username', models.CharField(blank=True, max_length=254)),
                ('attempted_password_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='honeypotevent',
            index=models.Index(fields=['ip_address', '-created'], name='honeypot_ho_ip_addr_a10f61_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotevent',
            index=models.Index(fields=['event_type', '-created'], name='honeypot_ho_event_t_77755a_idx'),
        ),
        migrations.AddIndex(
            model_name='honeypotevent',
            index=models.Index(fields=['-created'], name='honeypot_ho_created_8a441c_idx'),
        ),
    ]
