# Generated by Django 4.2.18 on 2026-05-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ended', 'Ended')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('mentor_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mentee_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentorshiprequest')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.JSONField(blank=True, default=list, help_text='List of tags / skill slugs.')),
                ('timezone_name', models.CharField(blank=True, max_length=64)),
                ('max_active_mentees', models.PositiveIntegerField(default=3)),
                ('is_accepting', models.BooleanField(default=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['mentor', 'status'], name='mentorship__mentor__6704dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorshiprequest',
            index=models.Index(fields=['mentee', 'status'], name='mentorship__mentee__59f9a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='mentorshiprequest',
            constraint=models.CheckConstraint(check=models.Q(('mentee', models.F('mentor')), _negated=True), name='mentee_neq_mentor'),
        ),
        migrations.AddIndex(
            model_name='mentorprofile',
            index=models.Index(fields=['is_accepting', '-avg_rating'], name='mentorship__is_acce_8b4dbc_idx'),
        ),
    ]
